language: scala
sudo: false

before_script:
- mkdir -p $HOME/.sbt/launchers/0.13.8/
- curl -L -o $HOME/.sbt/launchers/0.13.8/sbt-launch.jar http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar

scala:
   - 2.11.7

jdk: oraclejdk8

script: sbt ++$TRAVIS_SCALA_VERSION test